<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Zeta.Core.CSharp.Blake3</RootNamespace>
    <AssemblyName>Zeta.Core.CSharp.Blake3</AssemblyName>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Core/Core.fsproj" />
    <PackageReference Include="Blake3" />
  </ItemGroup>

</Project>
